### PR TITLE
[Merged by Bors] - feat: updated mqtt tutorial with transforms on inbound side

### PR DESCRIPTION
**Pull request by galibey**

### CODE REVIEW

**Review by ajhunyady — COMMENTED** [review]
Nice work, a few nits.

**Comment by ajhunyady** [comment]
I addd a bunch of comments... before `Review`... did they just get lost?

**Comment by galibey** [comment]
> I addd a bunch of comments... before `Review`... did they just get lost?

I can't see them here also but I got email notifications.

**Review by tjtelan — APPROVED** [review]
Nice, that was a lot of change. I like your new section too.

**Comment by tjtelan** [comment]
It looks like all the feedback was addressed. Gotta merge this now to support the current release!

bors r+

**Pull request closed without merging**
