### PR TITLE
chore: update sql-sink docs to include upsert

### PR DESCRIPTION
**Pull request by ozgrakkurt**

### CODE REVIEW

**Review by ajhunyady — APPROVED** [review]
Nice work!

**Comment by morenol** [comment]
@ozgrakkurt this doc should be automatically updated by this CI: https://github.com/infinyon/fluvio-website/actions/workflows/update-connector-docs.yml

**Comment by morenol** [comment]
I just triggered a run of that CI, but that basically fetches the readme from our connectors that are uploaded to the hub

**Comment by ozgrakkurt** [comment]
> I just triggered a run of that CI, but that basically fetches the readme from our connectors that are uploaded to the hub.
> 
> 
> 
> Update: 
> 
> 
> 
> CI triggered and not pr created. It seems that the last version uploaded to hub for this connector does not include those changes in the README, maybe we should create a new version instead? @ozgrakkurt 

Thanks! Yes the doc change was after publishing the connector. 

I'll bump and publish new version tomorrow 👍

**Comment by morenol** [comment]
> > I just triggered a run of that CI, but that basically fetches the readme from our connectors that are uploaded to the hub.
> > Update:
> > CI triggered and not pr created. It seems that the last version uploaded to hub for this connector does not include those changes in the README, maybe we should create a new version instead? @ozgrakkurt
> 
> Thanks! Yes the doc change was after publishing the connector.
> 
> I'll bump and publish new version tomorrow 👍

we can take advantage and update fluvio version anyways

**Comment by ozgrakkurt** [comment]
created PR: https://github.com/infinyon/sql-connector/pull/86

**Comment by ozgrakkurt** [comment]
closing in favor of https://github.com/infinyon/fluvio-website/pull/660

**Pull request closed without merging**
