### PR TITLE
Make tutorials visible again after merge conflicts

### PR DESCRIPTION
**Pull request by tjtelan**
This got lost after fixing the merge conflicts for last PR

### CODE REVIEW

**Comment by tjtelan** [comment]
bors ping

**Comment by tjtelan** [comment]
Fixing conflict rolled back CI workflow name changes
bors r-

**Comment by tjtelan** [comment]
One more time
bors r+

**Comment by tjtelan** [comment]
bors didn't start a required test
bors r-

**Comment by tjtelan** [comment]
Rust client example is failing since the recent update. Need to fix.
bors r-

**Review by morenol — APPROVED** [review]

**Pull request merged**
