### PR TITLE
Add bors config

### LINKED ISSUE #103: use bors for merging

### PR DESCRIPTION
**Pull request by nicholastmosher**
Closes #103

### CODE REVIEW

**Comment by nicholastmosher** [comment]
bors ping

**Comment by ajhunyady** [comment]
@nicholastmosher this seems to be an unfinished task.

**Comment by nicholastmosher** [comment]
This ended up being tricky because Bors needs to be able to kick off CI jobs by pushing to a branch called `staging`, but I don't know how netlify is hooked into the GH flow, it is not using GH actions. @ajhunyady we would probably have to sit down and look through the Netlify configuration options to make this work.

**Comment by nicholastmosher** [comment]
Decided we don't really need Bors in this repo, closing.

**Pull request closed without merging**
